[package]
name = "makemake"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
eyre = "0.6.8"
pathdiff = "0.2.1"
serde = { version = "1.0.152", features = ["derive"]}
serde_json = "1.0.93"
utf8-read = "0.4.0"
