[package]
name = "makemake"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
result = "1.0.0"
serde = { version = "1.0.152", features = ["derive"]}
serde_json = "1.0.93"
termal = "1.0.1"
thiserror = "1.0.56"
utf8-chars = "3.0.1"
